### ISSUE TITLE
Bump to version 1.6.1

### ISSUE THREAD

**Issue by gorillapower** [flathub/com.github.IsmaelMartinez.teams_for_linux#115]
Any chance to bump this to version 1.6.1? https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.6.1

**Comment by JGMelon22** [comment]
Really would like too :(

**Comment by IsmaelMartinez** [comment]
1.7.3 is out. Name of the app changed to portal for teams. See the trademark issue for more info
