### ISSUE TITLE
Crash when sharing screen when on Wayland

### ISSUE THREAD

**Issue by MightyCreak** [flathub/com.github.IsmaelMartinez.teams_for_linux#12]
Hi!

Thanks for packaging this application, it's the main communication channel in our company.

I had to switch back to Xorg because sharing the screen when on Wayland is actually crashing the application (may not be the packaging fault though, but before opening a ticket to Microsoft, I wanted to ask here first).

Cheers!

**Comment by IsmaelMartinez** [comment]
Hi,

This is not an official version of the MS teams app, but an unofficial that
was available a while back.

Some people have reported issues with the official app (many in my company)
as it seems to spike the CPU usage after each call.

Check the snap or deb/rpm packages available. I sort of not support neither
snap nor flatpak but sort of support them indirectly.

Cheers,
Ismael Martinez

**Comment by MightyCreak** [comment]
I'm not sure I understand. Basically you're saying that this flatpak package is no longer maintained?

**Comment by MightyCreak** [comment]
Oh I see, this repo is not the one for `com.microsoft.Teams`?

**Comment by IsmaelMartinez** [comment]
this repo is for https://github.com/IsmaelMartinez/teams-for-linux . Microsoft only provides deb and rpm

**Comment by MightyCreak** [comment]
I've opened an issue on the right repo this time: https://github.com/flathub/com.microsoft.Teams/issues/23

I'll close this one then. Thanks!
