### ISSUE TITLE
Custom Background Image

### ISSUE THREAD

**Issue by joaopblume** [flathub/com.github.IsmaelMartinez.teams_for_linux#128]
Hello, is there a way to add a custom background image? Not the default ones.

**Comment by IsmaelMartinez** [comment]
Hi, please refer to the https://github.com/IsmaelMartinez/teams-for-linux/issues for reporting (or asking) for issues that aren't related to the packaging of the package.

You can indeed have custom background images BUT you need to have a small server running in your machine. 

There is more info in https://github.com/IsmaelMartinez/teams-for-linux/tree/develop/app/config#custom-backgrounds and an example of a server implementation in https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/customBackground/example/README.md
