### ISSUE TITLE
Spellcheck not working. 

### ISSUE THREAD

**Issue by ECiurleo** [flathub/com.github.IsmaelMartinez.teams_for_linux#129]
I have spellcheck enabled in the application
![Screenshot from 2024-09-10 15-18-16](https://github.com/user-attachments/assets/116e39d3-3c1a-4971-822a-5f7fceb8e516)

But it appears the spelling spellcheck isn't enabled
![Screenshot from 2024-09-10 15-18-59](https://github.com/user-attachments/assets/660c971c-a76d-49af-aa3e-02dec9357543)

Steps to reproduce on Fedora 40 workstation;

1. Open Software (46.4)
2. Search for and install Portal for Teams (1.10.1)
3. Enable Spellcheck in Settings
4. Type badly...

**Comment by IsmaelMartinez** [comment]
Hi, please refer to the https://github.com/IsmaelMartinez/teams-for-linux/issues/ and the https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/KNOWN_ISSUES.md#spellchecker-not-working (the issue/solution is old, so it might not be working anymore)

This repo is for the packaging section. 

Spellcheck can also be a pain for some system and packaging options. Check also if one of the other packaging options we provide helps you, it could be a flathub issue only.

Hope helps (closing here as having 2 places for issues makes life harder)
