### ISSUE TITLE
Can't share just application

### ISSUE THREAD

**Issue by MightyCreak** [flathub/com.github.IsmaelMartinez.teams_for_linux#13]
Hi!

The Windows version allows to share just one application instead of the entire screen, but it is not available when using Teams on Linux (tested with flatpak only). I wonder if that could be a problem with Flatpak rights maybe?

Thanks!

**Comment by IsmaelMartinez** [comment]
Hi,

I can share only one application. The only limitation on that aspect is
that you can't share only one monitor (if you got multiple ones) but you
can choose just one application.

I don't support the flatpak version nor the snap one, just the deb/rpm ones
that are in the repo. Maybe git them a try and see if there is any
difference.

Hope helps,
Ismael

**Comment by MightyCreak** [comment]
I haven't tested with rpm yet, but if you're right, that would mean that it could be fixed by changing some rights in this flatpak package?

**Comment by IsmaelMartinez** [comment]
Check the packages in https://github.com/IsmaelMartinez/teams-for-linux (releases) and give it a go if you want. Hope helps.

**Comment by MightyCreak** [comment]
I opened an issue in the right repo this time ;)
https://github.com/flathub/com.microsoft.Teams/issues/22

It seems to be a missing feature from upstream in Teams for Linux.
I'll close this issue then, thanks!
