### ISSUE TITLE
Cannot Open Link 

### ISSUE THREAD

**Issue by maymage** [flathub/com.github.IsmaelMartinez.teams_for_linux#26]
of type `https://teams.live.com/meet/...`

It seems, the xdg-open properties do not work correctly. The snap install works though. 

See https://github.com/IsmaelMartinez/teams-for-linux/issues/89

Best

**Comment by jijojosephk** [comment]
@maymage can you try with the latest version?

**Comment by maymage** [comment]
Works \o/

**Comment by jijojosephk** [comment]
Closing as it works now.
