### ISSUE TITLE
Stuck at version 1.0.45 (3 months old, current version is 1.0.49)

### ISSUE THREAD

**Issue by kupiqu** [flathub/com.github.IsmaelMartinez.teams_for_linux#27]
Is the flatpak packaging maintained or do we need to move to deb/snap packages? thanks

**Comment by jijojosephk** [comment]
Yes, it is maintained. 1.0.49 was not officially released that's why. I had been busy and looking for electron version upgrade but electron `22.0.3` broke the system tray. No clue on how to fix.

**Comment by JGMelon22** [comment]
Version 1.0.50 just rolled out today (2023-03-02), any news to update the flatpak version?

**Comment by jijojosephk** [comment]
Latest build in progress [25897](https://buildbot.flathub.org/#/builders/6/builds/25897)

**Comment by JGMelon22** [comment]
You rock, man <3

**Comment by damentz** [comment]
Ran the latest flatpak on flathub, 1.0.50.  Systray icon works and everything else.  Thanks!

**Comment by marbub** [comment]
Is there a reason why you still use the 21.08 runtime. AFAIK there is already 22.8.

**Comment by jijojosephk** [comment]
New build is on the way with `22.08`, I've marked you in the other issue [698](https://github.com/IsmaelMartinez/teams-for-linux/issues/698#issuecomment-1459533852). Closing this since it's addressed.

**Comment by marbub** [comment]
The build with 20.08 works for me very well.
