### ISSUE TITLE
screesaver not inhibited

### ISSUE THREAD

**Issue by muelli** [flathub/com.github.IsmaelMartinez.teams_for_linux#34]
It seems that the app does not inhibit the screensaver so that my screen gets locked after being on a call for longer than five minutes. I haven't checked the upstream app whether it inhibits the screensaver but from looking at [the permissions](https://github.com/flathub/com.github.IsmaelMartinez.teams_for_linux/blob/16e4af831cf23a66ad97834dd8c0b44c974ac19d/com.github.IsmaelMartinez.teams_for_linux.yml#L21) it couldn't, even it wanted to.
Some other apps seems to be using `--talk-name=org.freedesktop.login1` or `--talk-name=org.freedesktop.PowerManagement.Inhibit`.

**Comment by jijojosephk** [comment]
can you allow `socket=session-bus` and see if it's working?

**Comment by jijojosephk** [comment]
Can you check the latest version?

**Comment by muelli** [comment]
I think it works. The permissions added in https://github.com/flathub/com.github.IsmaelMartinez.teams_for_linux/commit/7a7b391123831ef88f91cdfaf3e88f956019d211 seem to be too broad.
Maybe I can spy on the dbus traffic somehow to see the actual call the app makes.

**Comment by jijojosephk** [comment]
Closing as it's working.
