### ISSUE TITLE
Summary shouldn't name electron

### ISSUE THREAD

**Issue by razzeee** [flathub/com.github.IsmaelMartinez.teams_for_linux#59]
The summary should not mention technical details, such as the usage of electron

The description also needs work. Listing features would be nicer.

Reiterating the summary is a no go in the description.

**Comment by IsmaelMartinez** [comment]
Can you provide an alternative summary and description? Thanks

**Comment by razzeee** [comment]
Hopefully https://github.com/IsmaelMartinez/teams-for-linux/pull/1311 is a bit better/to your liking
