### ISSUE TITLE
[Feature Request] Option for enabling Wayland support by environment variable

### ISSUE THREAD

**Issue by p1gp1g** [flathub/com.github.IsmaelMartinez.teams_for_linux#72]
I wish I could run teams for linux with wayland support with an environment variable.

This can be done this way: https://github.com/flathub/org.signal.Signal/blob/9eda9228fc60326132ec7b8b2532475aa3d6708d/signal-desktop.sh

**Comment by jijojosephk** [comment]
It automatically detects whether it's running under Wayland or not and adds necessary flags. Isn't it working for you?

**Comment by p1gp1g** [comment]
If I remove socket=x11 and share=ipc argument, then launching teams-for-linux with the .desktop app or with the following command doesn't work :

`flatpak run --branch=stable --arch=x86_64 --command=teams-for-linux -
-file-forwarding com.github.IsmaelMartinez.teams_for_linux`

I have to run this command in order to launch it : 
`flatpak run --branch=stable --arch=x86_64 --command=teams-for-linux -
-file-forwarding com.github.IsmaelMartinez.teams_for_linux --ozone-platform=wayland --enable-features=W
aylandWindowDecorations`

But it is much more cleaner/easier to add an environment variable to the flatpak app (with flatseal or manually edditing `.local/share/flatpak/overrides/com.github.IsmaelMartinez.teams_for_linux`) than editing the .desktop file

**Comment by Mikaela** [comment]
Done by upstream Electron as `$ELECTRON_OZONE_PLATFORM_HINT`.

- https://www.electronjs.org/docs/latest/api/environment-variables#electron_ozone_platform_hint-linux
