### ISSUE TITLE
Screen sharing does not work

### ISSUE THREAD

**Issue by adamj-codethink** [flathub/com.github.IsmaelMartinez.teams_for_linux#8]
Hi there,

Great app, it has helped me a lot, thanks for packing this up!

However one problem i have is screen sharing does not work, i can select the sharing option when on a video call, but it shows nothing to share.

Any idea if this is a sandbox issue?

**Comment by gabops** [comment]
The changes have been merged into master after testing it. It will be available as upgrade and in the flathub store soon.

Thank you all for your support.

Regards
